from staze import Error


class TaskError(Error): pass